#!/usr/bin/env python3
"""
Generic ZXP to Boriel Basic Converter
Converts ZXP bitmap data to Boriel Basic DIM declarations.
"""

import argparse
import sys
import os

def read_zxp_file(filename):
    """Reads the .zxp file and extracts sprite lines, skipping header."""
    try:
        with open(filename, 'r') as f:
            lines = f.readlines()
        
        # Skip header (first 2 lines usually, but we filter by content)
        # ZXP files often start with metadata lines like '0F' or '47' or dimensions
        # We'll filter for lines that look like bitmap data (0s and 1s) or are part of the grid
        # The original script skipped first 2 lines and filtered specific starts.
        # We will follow a similar robust approach but try to be generic.
        
        sprite_lines = [
            line.strip() 
            for line in lines[2:] 
            if line.strip() and not line.startswith('0F') and not line.startswith('47')
        ]
        return sprite_lines
    except Exception as e:
        print(f"Error reading file {filename}: {e}")
        sys.exit(1)

def extract_sprite(lines, row, col, width):
    """
    Extracts a sprite of size width x width from the grid.
    row: grid row index
    col: grid col index
    width: width/height of the sprite in pixels
    """
    sprite = []
    start_col = col * width
    start_row = row * width
    
    for y in range(width):
        if start_row + y < len(lines):
            line = lines[start_row + y]
            # Ensure line is long enough
            if start_col + width <= len(line):
                sprite_row = line[start_col:start_col + width]
                sprite.append(sprite_row)
            else:
                sprite.append("0" * width)
        else:
            sprite.append("0" * width)
    
    return sprite

def bitmap_to_bytes(sprite, width):
    """
    Converts a bitmap sprite to bytes in interleaved format for putChars.
    Assumes width is a multiple of 8.
    """
    bytes_data = []
    
    chars_per_row = width // 8
    chars_per_col = width // 8 # Square tiles
    
    # Iterate through character blocks (columns then rows)
    # Note: The original script iterated col_block then row_block.
    # We will stick to that order as it seems standard for this putChars routine.
    
    for col_block in range(chars_per_col):
        for row_block in range(chars_per_row):
            # 8 lines per character
            for y_offset in range(8):
                byte_val = 0
                y = row_block * 8 + y_offset
                
                # 8 pixels per byte
                for x_offset in range(8):
                    x = col_block * 8 + x_offset
                    
                    if y < len(sprite) and x < len(sprite[y]):
                        if sprite[y][x] == '1':
                            byte_val |= (1 << (7 - x_offset))
                            
                bytes_data.append(byte_val)
    
    return bytes_data

def format_bytes(bytes_data):
    """Formats bytes into hex strings for ZX BASIC."""
    hex_strings = ['$' + format(b, '02X') for b in bytes_data]
    
    # Split into lines of 8 bytes for readability
    lines = []
    for i in range(0, len(hex_strings), 8):
        line = ','.join(hex_strings[i:i+8])
        if i + 8 < len(hex_strings):
            line += ','
        lines.append(line)
    
    return ' _\n\t\t'.join(lines)

def main():
    parser = argparse.ArgumentParser(description='Convert ZXP sprites to Boriel Basic.')
    parser.add_argument('--input', '-i', required=True, help='Input .zxp file')
    parser.add_argument('--width', '-w', type=int, required=True, help='Tile width (pixels)')
    parser.add_argument('--rows', '-r', type=int, required=True, help='Number of rows')
    parser.add_argument('--cols', '-c', type=int, required=True, help='Number of columns')
    parser.add_argument('--output', '-o', required=True, help='Output .bas file')
    parser.add_argument('--name', '-n', required=True, help='Variable name prefix')
    
    args = parser.parse_args()
    
    if args.width % 8 != 0:
        print("Error: Width must be a multiple of 8.")
        sys.exit(1)
        
    lines = read_zxp_file(args.input)
    
    # Calculate total size of one sprite in bytes
    total_bytes = (args.width // 8) * (args.width // 8) * 8
    # Array size is total_bytes - 1 (0-indexed)
    
    total_sprites = args.rows * args.cols
    
    with open(args.output, 'w') as f:
        f.write(f"' Generated by zxp2boriel.py\n")
        f.write(f"' Source: {os.path.basename(args.input)}\n")
        f.write(f"' Size: {args.width}x{args.width}\n")
        f.write(f"' Count: {total_sprites}\n\n")
        
        f.write(f"Dim {args.name}({total_sprites - 1}, {total_bytes - 1}) As Ubyte => {{ _\n")
        
        count = 0
        for r in range(args.rows):
            for c in range(args.cols):
                sprite = extract_sprite(lines, r, c, args.width)
                bytes_data = bitmap_to_bytes(sprite, args.width)
                formatted_data = format_bytes(bytes_data)
                
                f.write(f"\t{{ _\n")
                f.write(f"\t\t{formatted_data} _\n")
                
                if count < total_sprites - 1:
                    f.write(f"\t}}, _\n")
                else:
                    f.write(f"\t}} _\n")
                
                count += 1
        
        f.write(f"}}\n")
                
    print(f"Successfully generated {count} sprites in {args.output}")

if __name__ == '__main__':
    main()
